import type { Article, ProductPick } from "./articles";

const DATE = "September 26, 2026";
const METHOD = "This review is based on the manufacturer’s current product page, published specifications, care information and publicly available owner feedback. TrailNestCo did not physically test this product. Prices, colours and availability can change; confirm details on the retailer’s page before buying.";

type K = {
  slug: string; title: string; excerpt: string; image: string; alt: string; name: string; bestFor: string;
  body: string; fabric: string; weight: string; specs: string; price: "$$" | "$$$"; url: string;
  pros: string[]; cons: string[]; takeaways: string[]; verdict: string; related: string[];
};

function createReview(k: K): Article {
  const pick: ProductPick = {
    name: k.name, award: "TrailNestCo pick", bestFor: k.bestFor, priceTier: k.price,
    image: k.image, imageAlt: k.alt, imageCredit: "Image: KETL Mtn.", body: k.body,
    pros: k.pros, cons: k.cons,
    keySpecs: [{ label: "Fabric / insulation", value: k.fabric }, { label: "Listed weight", value: k.weight }, { label: "Key details", value: k.specs }],
    ctaLabel: `Check ${k.name} on KETL Mtn.`, ctaUrl: k.url, ctaIsAffiliate: true,
  };
  return {
    slug: k.slug, type: "review", title: k.title, category: "Camping & Outdoor", author: "TrailNestCo Editorial", reviewer: "TrailNestCo Editorial", date: DATE, datePublished: "2026-09-26", dateModified: "2026-09-26", readTime: "8 min read", excerpt: k.excerpt, image: k.image, alt: k.alt, imageCredit: "Image: KETL Mtn.", howWeEvaluated: METHOD,
    intro: [k.body, "This is a research-based review, not a hands-on test. The useful question is whether the listed materials, weight and features solve your specific trip problem — heat, abrasion, secure storage or warmth — better than a simpler alternative."],
    keyTakeaways: k.takeaways,
    quickVerdict: k.verdict,
    picks: [pick],
    table: { headers: ["Detail", "Published information"], rows: [["Best for", k.bestFor], ["Fabric / insulation", k.fabric], ["Listed weight", k.weight], ["Notable details", k.specs]] },
    sections: [
      { heading: "What the published details suggest", body: [k.body, "Specifications help set expectations, but they do not replace fit, comfort and real-world weather judgment. Check the current KETL product page for the selected size and colour before ordering."] },
      { heading: "What to check before buying", list: ["Compare the current size chart with a garment you already own.", "Check the selected colour, size and availability on KETL’s official product page.", "Match the piece to the route: lightweight fabric and water resistance are not the same as durable or waterproof protection.", "Read current care instructions so the material performs as intended."] },
    ],
    buyingGuide: [{ heading: "Who this piece suits", list: [k.bestFor, "People who value a versatile outdoor/travel wardrobe", "Buyers who will verify fit and current specifications before ordering"] }],
    whoFor: [k.bestFor, "Travelers and outdoor users who prefer technical features in a simple silhouette"],
    whoShouldSkip: ["Anyone who needs a fully waterproof shell", "Buyers who need proven hands-on test data before purchasing"],
    verdict: k.verdict,
    faq: [
      { q: `Is the ${k.name} good for hiking?`, a: `It is most appropriate for ${k.bestFor}. Check the current product page and match it to your terrain, weather and activity level.` },
      { q: "Was this product physically tested by TrailNestCo?", a: "No. This review is based on current published product information and available owner feedback, as explained in our methodology." },
      { q: "Should I rely on the listed details?", a: "Treat published information as a guide, then confirm sizing, care, price and availability directly with KETL before buying." },
    ],
    related: k.related,
  };
}

export const ketlReviews: Article[] = [
  createReview({
    slug: "ketl-nofry-sun-hoodie-review", title: "KETL Mtn. NoFry Sun Hoodie Review: Ultralight Coverage for Hot Trails", excerpt: "A research-based look at KETL’s featherweight UPF 30+ sun hoodie: its best use cases, published details and key trade-offs.", image: "/images/ketl/KETL-Sun-Hoodie-Comparison-Hero-Desktop.webp", alt: "Hiker wearing a lightweight KETL Mtn sun hoodie outdoors", name: "KETL Mtn. NoFry Four Snap Sun Hoodie", bestFor: "hiking, paddling, trail running and travel in strong sun", body: "NoFry is built around very light grid-knit recycled polyester, a four-snap front and a hood that can sit over or under a cap. KETL lists a 79 gsm fabric, 114 g size-M weight and UPF 30+ minimum protection. It is an airflow-first sun layer, not an abrasion layer.", fabric: "100% recycled polyester, 79 gsm", weight: "114 g, size M", specs: "UPF 30+ minimum; four snaps; hood; thumbholes", price: "$$", url: "https://ketlmtn.com/products/nofry-sunhoodie?ref=hpakmutk", pros: ["Very low listed weight", "Published UPF 30+ minimum", "Snaps and thumbholes add coverage control"], cons: ["Light fabric needs care around rough surfaces", "Not an insulating layer", "UPF 30+ is lower than some UPF 50+ alternatives"], takeaways: ["The product page lists UPF 30+ minimum protection.", "The 79 gsm fabric targets airflow and packability.", "Best for exposed warm-weather movement, not abrasive terrain."], verdict: "Choose NoFry when staying cool and covered in strong sun matters more than durability. Treat it as a sun tool rather than a tough outer layer.", related: ["best-hiking-boots", "ketl-vent-pants-review", "ketl-shenanigan-pants-review"]
  }),
  createReview({
    slug: "ketl-vent-pants-review", title: "KETL Mtn. Vent Pants Review: A Lightweight Option for Hot-Weather Hikes", excerpt: "Vent Pants prioritise breathability and packability. See the current published fabric, weight and storage details before choosing them for hot trails.", image: "/images/ketl/KETL-Vent-Lightweight-Short-PDP-Green-1.webp", alt: "KETL Mtn lightweight Vent apparel in green", name: "KETL Mtn. Vent Lightweight Active Pants", bestFor: "warm hikes, camping and minimalist travel", body: "Vent Pants are designed for days when trousers still make sense but heavy fabric does not. KETL lists 135 gsm polyester, a 278 g size-M weight, a stretch waist, gusset and secure side and rear zip pockets. The product page does not list an official UPF rating.", fabric: "100% polyester, 135 gsm", weight: "278 g, size M", specs: "Stretch waist; drawstring; gusset; side and rear zip pockets", price: "$$", url: "https://ketlmtn.com/products/ketl-mtn-vent-joggerish-lightweight-travel-pants?ref=hpakmutk", pros: ["Light listed weight", "Airflow-first fabric", "Secure storage", "Packable travel-focused design"], cons: ["No official UPF rating listed", "Less abrasion-focused than nylon pants", "Slim fit requires careful sizing"], takeaways: ["KETL lists 135 gsm polyester and 278 g for size M.", "Secure pockets make them more practical than basic joggers.", "Choose them for heat and travel, not rugged brush."], verdict: "Vent Pants fit a narrow but common need: staying covered without heavy trousers in heat. Their light build is a strength if your route is not abrasive.", related: ["ketl-nofry-sun-hoodie-review", "ketl-shenanigan-pants-review", "how-to-waterproof-gear"]
  }),
  createReview({
    slug: "ketl-shenanigan-pants-review", title: "KETL Mtn. Shenanigan Pants Review: The Rugged Everyday Hiking Pant", excerpt: "A research-based review of KETL’s Shenanigan Pants: durable stretch nylon twill, secure pockets and fit trade-offs for hiking and travel.", image: "/images/ketl/KETL-Shenanigan-Shorts-4x5-Black-PDP-4.webp", alt: "KETL Mtn Shenanigan outdoor apparel in black", name: "KETL Mtn. Shenanigan Outdoor Pants", bestFor: "day hiking, travel and everyday wear when durability matters", body: "Shenanigan is KETL’s more robust everyday pant. The product page lists 96% nylon, 4% spandex twill at 156 gsm, a gusset, an internal G-hook belt and a water- and stain-resistant finish. It sits between a casual pant and a dedicated hiking trouser.", fabric: "96% nylon, 4% spandex; 156 gsm", weight: "332 g, size M", specs: "Water/stain-resistant finish; G-hook belt; rear and side zip pockets", price: "$$", url: "https://ketlmtn.com/products/shenanigan-pant?ref=hpakmutk", pros: ["Nylon-rich fabric is more abrasion-oriented", "Gusset supports movement", "Multiple secure pockets", "Straight and slim fit options"], cons: ["Heavier than a hot-weather specialist", "Water resistance is not waterproofing", "Fit must be chosen carefully"], takeaways: ["Manufacturer lists 96% nylon / 4% spandex at 156 gsm.", "Its storage and belt are useful for hiking and travel.", "A DWR-style finish does not replace rain pants."], verdict: "Shenanigan is the strongest all-round KETL pant for hiking, travel and everyday wear. Choose it for durability and storage, not as a waterproof layer.", related: ["ketl-vent-pants-review", "ketl-tomfoolery-chinos-review", "best-hiking-boots"]
  }),
  createReview({
    slug: "ketl-tomfoolery-chinos-review", title: "KETL Mtn. Tomfoolery Chinos Review: Travel Pants That Do Not Look Technical", excerpt: "Tomfoolery Chinos combine a discreet profile with stretch fabric and hidden storage. See where the travel-first design works best — and where a hiking pant wins.", image: "/images/ketl/KETL-Tomfoolery-Travel-Pant-Brown-PDP-5.webp", alt: "KETL Mtn Tomfoolery Chino Travel Pants in brown", name: "KETL Mtn. Tomfoolery Chino Travel Pants", bestFor: "flights, commuting, light hikes and one-bag travel", body: "Tomfoolery Chinos aim for a clean city-ready profile with travel details hidden in plain sight. KETL lists 222 gsm stretch-woven polyester, a 386 g size-M weight, belt loops, an internal drawstring and multiple zipper pockets. That makes them travel-first rather than heat-first.", fabric: "100% polyester, 222 gsm", weight: "386 g, size M", specs: "Internal drawstring; belt loops; front and rear zip pockets", price: "$$", url: "https://ketlmtn.com/products/tomfoolery-pant?ref=hpakmutk", pros: ["Clean chino-style appearance", "Multiple hidden secure pockets", "Stretch waist plus belt loops", "Listed wrinkle, stain and water resistance"], cons: ["Heavier than Vent Pants", "Not a waterproof pant", "Slim cut is tailored"], takeaways: ["KETL lists 222 gsm fabric and 386 g in size M.", "Hidden storage is the core travel advantage.", "Best for flights and city days with light hiking."], verdict: "Tomfoolery Chinos are a travel piece first and a light-hike option second. Their clean profile and secure storage make sense when your trip includes more than trails.", related: ["ketl-shenanigan-pants-review", "ketl-vent-pants-review", "best-travel-backpack-carry-on"]
  }),
  createReview({
    slug: "ketl-rockyloft-down-jacket-review", title: "KETL Mtn. RockyLoft Down Jacket Review: Packable Insulation for Cool Starts", excerpt: "RockyLoft pairs 800-fill down with pocket packability and underarm venting. See the published details and the conditions where it fits best.", image: "/images/ketl/KETL-RockyLoft-Insulated-Down-Jacket-Black-PDP-19.webp", alt: "KETL Mtn RockyLoft insulated down jacket in black", name: "KETL Mtn. RockyLoft Insulated Down Jacket", bestFor: "cool trailheads, travel and low-output camp time", body: "RockyLoft is a packable 800-fill down jacket with a PFAS-free DWR finish and laser-perforated underarms. Those details point to an insulation layer for cool, mostly dry conditions and stop-start activity, not a standalone shell for sustained rain.", fabric: "800-fill premium down insulation", weight: "Check current product page", specs: "Packs into left pocket; PFAS-free DWR; laser-perforated underarms", price: "$$$", url: "https://ketlmtn.com/products/rockyloft-insulated-down-jacket?ref=hpakmutk", pros: ["800-fill down targets warmth with low bulk", "Packs into its pocket", "Underarm vents manage heat", "DWR helps with light moisture"], cons: ["Not waterproof", "Down performs best when kept dry", "Premium price versus fleece"], takeaways: ["KETL lists 800-fill premium down insulation.", "The jacket packs into its left pocket.", "Use a shell when sustained rain is likely."], verdict: "RockyLoft is best viewed as a compact warmth layer. The published details make it a sensible choice for cool dry conditions, provided you layer a shell for real weather.", related: ["how-to-choose-a-sleeping-bag", "ketl-shenanigan-pants-review", "best-camping-tents-review"]
  }),
];
